# Generated by Django 4.0 on 2022-05-17 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
        ('seed', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Standings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('points', models.IntegerField()),
                ('games', models.IntegerField()),
                ('won', models.IntegerField()),
                ('drawn', models.IntegerField()),
                ('lost', models.IntegerField()),
                ('goal_for', models.IntegerField()),
                ('goal_against', models.IntegerField()),
                ('goal_difference', models.IntegerField()),
                ('points_percentage', models.FloatField()),
                ('position_variation', models.IntegerField()),
                ('last_results', models.CharField(max_length=45)),
                ('championship_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seed.championshiptable')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team')),
            ],
        ),
    ]
