# Generated by Django 4.0 on 2022-04-09 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                ("team_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=45)),
                ("abbreviation", models.CharField(max_length=5)),
                ("crest", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
