# Generated by Django 4.0 on 2022-05-18 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("seed", "0002_standings"),
        ("users", "0001_initial"),
        ("bets", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BetRanking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_points", models.IntegerField()),
                (
                    "championship_table",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="seed.championshiptable",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.user"
                    ),
                ),
            ],
        ),
    ]
